name: .NET Core Desktop

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: ssh-vpn.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name

    - name: Build the solution
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ssh-vpn-${{ matrix.configuration }}
        path: ssh-vpn/bin/${{ matrix.configuration }}
